name: Testing

on:
  push:
    branches:
      - 'master'
    tags:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

concurrency:
  # Update of a developer branch cancels the previously scheduled workflow run
  # for this branch. However, the 'master' branch and tag workflow runs are
  # never canceled.
  #
  # We use the following hack: define the concurrency group as 'workflow run ID'
  # + 'workflow run attempt' because it is a unique combination for any run. So
  # it effectively discards grouping.
  #
  # XXX: we cannot use `github.sha` as a unique identifier because pushing a tag
  # may cancel a run that works on a branch push event.
  group: ${{ (
    github.ref == 'refs/heads/master' ||
    startsWith(github.ref, 'refs/tags/')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        BUILDTYPE: [Debug, Release]
        OS: [Linux, macOS]
        LIBTYPE: [shared, static]
        CC: [GCC, Clang]
        include:
          - OS: Linux
            RUNNER: [ubuntu-20.04]
            TESTOPTIONS: -DUJIT_TEST_OPTIONS=-O4
          - OS: macOS
            RUNNER: [macos-12]
          - CC: Clang
            TOOLCHAIN: -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/Clang.cmake
        exclude:
          # XXX: Strictly saying, macOS simply aliases `gcc' to AppleClang
          # compiler, and this exclude rule just signals that AppleClang
          # doesn't need any extra tweaks of the testing environment.
          - OS: macOS
            CC: Clang
          - OS: macOS
            LIBTYPE: shared
    runs-on: ${{ matrix.RUNNER }}
    name: >
      ${{ matrix.OS }}
      ${{ matrix.CC }}
      ${{ matrix.BUILDTYPE }}
      ${{ matrix.LIBTYPE }}
    steps:
      - uses: actions/checkout@v3
      - name: setup Linux
        uses: ./.github/actions/setup-linux
        if: ${{ matrix.OS == 'Linux' }}
      - name: setup macOS
        uses: ./.github/actions/setup-macos
        if: ${{ matrix.OS == 'macOS' }}
      - name: configure
        run: >
          cmake -S . -B ${{ env.BUILDDIR }}
          -DCMAKE_BUILD_TYPE=${{ matrix.BUILDTYPE }}
          -DUJIT_TEST_LIB_TYPE=${{ matrix.LIBTYPE }}
          ${{ matrix.TOOLCHAIN }}
          ${{ matrix.TESTOPTIONS }}
      - name: build
        run: cmake --build . --parallel
        working-directory: ${{ env.BUILDDIR }}
      - name: test
        run: cmake --build . --parallel --target tests
        working-directory: ${{ env.BUILDDIR }}
